# netlify.toml

[build]
  # Build command for the frontend (client)
  command = "cd client && npm install && npm run build"

  # Publish directory for the frontend build output
  publish = "client/build"

  # Build command for the backend (Flask)
  functions = "flask-server/"

  # Specify Python version and dependencies
  [[plugins]]
    package = "@netlify/plugin-python"
    [plugins.inputs]
      python_version = "3.8"
      requirements = "requirements.txt"

[[redirects]]
  # Redirects for client-side routing (adjust as needed)
  from = "/*"
  to = "/index.html"
  status = 200
