[build]
  # Frontend build command
  command = "cd client && npm install && npm run build"  # Change this to your frontend build command

  # Backend build command
  functions = "flask-server"  # Specify the directory where your backend functions reside

  # Publish directory for the frontend build output
  publish = "client/build"

[build.environment]
  # Backend build command with virtual environment activation and gunicorn
  FLASK_ENV = "production"
  FLASK_APP = "server:app"
  PYTHON_VERSION = "3.8"

[build.processing]
  # Backend build command with virtual environment activation and gunicorn
  shell = "/bin/bash -c 'cd flask-server && source venv/bin/activate && gunicorn -w 4 -b 127.0.0.1:5000 server:app'"

[[redirects]]
  # Redirects for client-side routing (adjust as needed)
  from = "/*"
  to = "/index.html"
  status = 200
