[build]
  # Build command for the frontend (client) & backend flask-server
  command = "cd client && npm install && npm run build && cd flask-server && source venv/bin/activate && gunicorn -w 4 -b 127.0.0.1:5000 server:app"

  # Publish directory for the frontend build output
  publish = "client/build"

[[redirects]]
  # Redirects for client-side routing (adjust as needed)
  from = "/*"
  to = "/index.html"
  status = 200