# netlify.toml

[build]
  # Build command for the frontend (client)
  command = "cd client && npm install && npm run build"

  # Publish directory for the frontend build output
  publish = "client/build"

  # Build command for the backend (Flask)
  functions = "flask-server/"

  # Install Python dependencies
  command = "pip3 install -r requirements.txt"

[[redirects]]
  # Redirects for client-side routing (adjust as needed)
  from = "/*"
  to = "/index.html"
  status = 200
